#ifndef ATTACKATLANTIS_ENEMYTYPE_HPP
#define ATTACKATLANTIS_ENEMYTYPE_HPP

enum class EnemyType {
    BASIC,
    SHOOTING,
    SPEED,
    BOSS,
    BOSS2,
    NO_ENEMY
};

#endif //ATTACKATLANTIS_ENEMYTYPE_HPP
