#ifndef ATTACKATLANTIS_ENTITYTYPE_HPP
#define ATTACKATLANTIS_ENTITYTYPE_HPP

enum class EntityType {
    OTHERS,
    THEGUY,
    ENVIRONMENT,
    ENEMY,
    PET,
    ROCK,
    PROJECTILE,
    ABILITY_CONTAINER,
    ENEMY_PROJECTILE,
    BOOMERANG_PROJECTILE,
    WATERCURRENT,
    GLYPH,
    PARTICLE,
    FOOD,
};

#endif //ATTACKATLANTIS_ENTITYTYPE_HPP
