#ifndef ATTACKATLANTIS_LEVELNAME_HPP
#define ATTACKATLANTIS_LEVELNAME_HPP

enum class LevelName {
    LEVEL_ONE,
    LEVEL_TWO,
    LEVEL_THREE,
    LEVEL_FOUR,
    LEVEL_FIVE,
    LEVEL_SIX,
    LEVEL_SEVEN,
    LEVEL_EIGHT,
    LEVEL_NINE,
    LEVEL_TEN,
    VICTORY_PAGE,
    DEFEAT_PAGE,
    SURVIVAL_MODE,
    TUTORIAL_LEVEL,
    NO_LEVEL,
    MAIN_MENU,
    LEVEL_SELECTION,
    LEADERBOARD
};

#endif